version: 1.0

networks:
  test:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
